@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.edwinmindcraft.origins.api.capabilities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;